- hosts: all
  remote_user: isadmin
  become: yes
  become_method: sudo
  gather_facts: no
  pre_tasks:
  - name: Install python
    raw: bash -c "test -e /usr/bin/python || (yum -y install python || (apt-get -qqy update && apt-get -qqy install python))"
  - name: Gathering facts
    setup:
###
  - name: upgrade all packages
    yum:
      name: '*'
      state: latest
###
  - name: Install epel and enable extras
    shell: |
      wget http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      rpm -ivh epel-release-latest-7.noarch.rpm
      yum-config-manager --enable extras
###
  - name: ensure a list of packages installed
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
###
  - name: ensure a list of packages removed 
    yum:
      name: "{{ packages }}"
      state: absent
    vars:
      packages:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-selinux
      - docker-engine-selinux
      - docker-engine
###
  - name: Add repository
    command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
###
  - name: install the latest version of docker-ce
    yum:
      name: docker-ce
      state: latest
